language: ruby
rvm:
  - 2.1.5
  - 2.2.0
  - rbx-2
addons:
  postgresql: '9.4'
before_install:
  - gem update --system
  - gem --version
  - gem install bundler
before_script:
  - bundle exec rake db:create
  - bundle exec rake db:migrate
cache: bundler
