language: ruby
rvm:
  - 2.1.5
  - 2.2.0
addons:
  postgresql: '9.4'
before_install:
  - gem update --system
  - gem --version
  - gem install bundler
before_script:
  - bundle exec rake db:create
  - bundle exec rake db:migrate
cache: bundler
gemfile:
  - gemfiles/activerecord_4.2.1.gemfile
  - gemfiles/activerecord_4.2.2.gemfile
  - gemfiles/activerecord_4.2.3.gemfile
  - gemfiles/activerecord_4.2.4.gemfile
